# TUM RGB-D fr1_desk Camera Intrinsics
Camera:
  name: "TUM fr1_desk"
  width: 640
  height: 480
  
  # Intrinsic parameters
  fx: 517.306408
  fy: 516.469215
  cx: 318.64304
  cy: 255.313989
  
  # Distortion coefficients (radial + tangential)
  distorted: true
  k1: 0.262383
  k2: -0.953104
  k3: 1.163314
  p1: -0.005358
  p2: 0.002628
  
  # Depth parameters
  depth_scale: 5000.0
